services:

  postgres:
    image: postgres:17
    container_name: ccs-postgres

    environment:
      POSTGRES_DB: ccs_db
      POSTGRES_USER: ccs_user
      POSTGRES_PASSWORD: ccs_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ccs_user -d ccs_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  ccs-app:
    build: .
    container_name: ccs-app

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      SPRING_PROFILES_ACTIVE: docker

    ports:
      - "8080:8080"

    restart: unless-stopped

volumes:
  postgres_data: