services:
  postgres:
    image: postgres:17
    container_name: ccs-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ccs_db
      POSTGRES_USER: ccs_user
      POSTGRES_PASSWORD: ccs_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
