server:
  port: 8080

spring:

  datasource:
    url: jdbc:postgresql://ccs-postgres:5432/ccs_db
    username: ccs_user
    password: ccs_password
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.ccs: DEBUG

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui.html