server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://dev-db:5432/ccs_db
    username: dev_user
    password: dev_password

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
